# -*- coding: utf-8 -*-
"""Tarea-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zf-E2ncW_P7Ova4eF-kYU6x5-T3sjGlS
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# 1. Cargar el dataset
df = pd.read_csv('/content/home_data.csv')

"""**Exploración básica**"""

print(df.head())

print(df.info())

print(df.describe())

"""**manejo de valores nulos**"""

df = df.dropna()

"""**codificacion de variables categoricas**

"""

label_encoders = {}
for column in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le

"""**escalar caracteristicas numericas**"""

scaler = StandardScaler()
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = scaler.fit_transform(df[num_cols])

"""**Separar variables dependientes e independientes**"""

X = df.drop('price', axis=1)  # Cambia 'target' por tu columna objetivo
y = df['price']

"""**Division dataset en train y test**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.head()

X_test.head()